### ISSUE TITLE
Molotov for vim, GVim, and MacVim link broken

### ISSUE THREAD

**Issue by wayneashleyberry** [gf3/butt.zone#4]
The link to Molotov for vim, GVim, and MacVim is pointing to

→ https://raw.githubusercontent.com/gf3/dotfiles/master/.nvim/colors/molotov.vim

it should be pointing to

→ https://raw.githubusercontent.com/gf3/dotfiles/master/.config/nvim/colors/molotov.vim

**Comment by gf3** [comment]
fixed thanks! lol i don't think i ever got an email for this issue
